import { colors } from './colors';

export const predefinedCategories = [
  {
    id: 'grocery',
    name: 'Grocery',
    type: 'expense',
    icon: 'shopping-cart',
    color: colors.grocery,
  },
  {
    id: 'transport',
    name: 'Transport',
    type: 'expense',
    icon: 'car',
    color: colors.transport,
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    type: 'expense',
    icon: 'film',
    color: colors.entertainment,
  },
  {
    id: 'utilities',
    name: 'Utilities',
    type: 'expense',
    icon: 'zap',
    color: colors.utilities,
  },
  {
    id: 'housing',
    name: 'Housing',
    type: 'expense',
    icon: 'home',
    color: colors.housing,
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    type: 'expense',
    icon: 'heart',
    color: colors.healthcare,
  },
  {
    id: 'dining',
    name: 'Dining',
    type: 'expense',
    icon: 'coffee',
    color: colors.dining,
  },
  {
    id: 'shopping',
    name: 'Shopping',
    type: 'expense',
    icon: 'shopping-bag',
    color: colors.shopping,
  },
  {
    id: 'other_expense',
    name: 'Other',
    type: 'expense',
    icon: 'more-horizontal',
    color: colors.other,
  },
  {
    id: 'salary',
    name: 'Salary',
    type: 'income',
    icon: 'briefcase',
    color: colors.income,
  },
  {
    id: 'freelance',
    name: 'Freelance',
    type: 'income',
    icon: 'edit',
    color: colors.income,
  },
  {
    id: 'investment',
    name: 'Investment',
    type: 'income',
    icon: 'trending-up',
    color: colors.income,
  },
  {
    id: 'gift',
    name: 'Gift',
    type: 'income',
    icon: 'gift',
    color: colors.income,
  },
  {
    id: 'other_income',
    name: 'Other',
    type: 'income',
    icon: 'more-horizontal',
    color: colors.income,
  },
];